title: Nick Carroll # your name (or website title) here
logo: "https://avatars.githubusercontent.com/u/5028048?s=400&u=7580223635e88afa5ec411e42e0ff49bbaadbae9&v=4" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pardon the dust...
  <br><br>
  ... This will be updated soon enough!
  <br><br>
  <a href="http://linkedin.com/nick-carroll1">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
